// Demo data for dashboard pages when database is empty

import type {
  Farm,
  Task,
  User,
  Transaction,
  Sale,
  Crop,
  RoadmapPhase,
  Milestone,
  Livestock,
} from "@/types";

export const demoFarms: Farm[] = [
  {
    id: "demo-farm-1",
    name: "Ferme Manguier Bobo",
    location: "Bobo-Dioulasso",
    country: "burkina_faso",
    sizeHectares: "45.5",
    latitude: "11.1771",
    longitude: "-4.2979",
    description: "Main mango and cashew production farm with irrigation system",
    managerId: "demo-user-1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-farm-2",
    name: "Ferme Ananas Sikasso",
    location: "Sikasso",
    country: "mali",
    sizeHectares: "32.0",
    latitude: "11.3167",
    longitude: "-5.6667",
    description: "Pineapple and banana plantation near the river",
    managerId: "demo-user-2",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "demo-farm-3",
    name: "Ferme Cashew Maradi",
    location: "Maradi",
    country: "niger",
    sizeHectares: "28.5",
    latitude: "13.5000",
    longitude: "7.1000",
    description: "Cashew and papaya farm with drip irrigation",
    managerId: "demo-user-3",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-farm-4",
    name: "Ferme Banane Ouaga",
    location: "Ouagadougou",
    country: "burkina_faso",
    sizeHectares: "18.0",
    latitude: "12.3714",
    longitude: "-1.5197",
    description: "Urban banana and avocado farm",
    managerId: "demo-user-1",
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-farm-5",
    name: "Ferme Papaye Bamako",
    location: "Bamako",
    country: "mali",
    sizeHectares: "22.0",
    latitude: "12.6392",
    longitude: "-8.0029",
    description: "Papaya and mango cooperative farm",
    managerId: "demo-user-2",
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-11-10"),
  },
];

export const demoCrops: Crop[] = [
  {
    id: "demo-crop-1",
    fieldId: "demo-field-1",
    cropType: "mango",
    variety: "Kent",
    status: "fruiting",
    plantingDate: new Date("2022-06-15"),
    expectedHarvestDate: new Date("2024-12-01"),
    actualHarvestDate: null,
    numberOfPlants: 250,
    expectedYieldKg: "12500",
    actualYieldKg: null,
    notes: "Premium export variety, third season",
    imageUrl: null,
    createdAt: new Date("2022-06-15"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-crop-2",
    fieldId: "demo-field-2",
    cropType: "cashew",
    variety: "Local improved",
    status: "growing",
    plantingDate: new Date("2023-07-01"),
    expectedHarvestDate: new Date("2025-02-15"),
    actualHarvestDate: null,
    numberOfPlants: 180,
    expectedYieldKg: "5400",
    actualYieldKg: null,
    notes: "First harvest expected next year",
    imageUrl: null,
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "demo-crop-3",
    fieldId: "demo-field-3",
    cropType: "pineapple",
    variety: "Cayenne",
    status: "harvesting",
    plantingDate: new Date("2024-01-15"),
    expectedHarvestDate: new Date("2024-11-30"),
    actualHarvestDate: null,
    numberOfPlants: 5000,
    expectedYieldKg: "7500",
    actualYieldKg: "6800",
    notes: "Sweet Cayenne for local market",
    imageUrl: null,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-crop-4",
    fieldId: "demo-field-4",
    cropType: "banana",
    variety: "Plantain",
    status: "fruiting",
    plantingDate: new Date("2024-03-01"),
    expectedHarvestDate: new Date("2024-12-15"),
    actualHarvestDate: null,
    numberOfPlants: 800,
    expectedYieldKg: "16000",
    actualYieldKg: null,
    notes: "Organic plantain for hotels",
    imageUrl: null,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-11-19"),
  },
  {
    id: "demo-crop-5",
    fieldId: "demo-field-5",
    cropType: "papaya",
    variety: "Solo",
    status: "harvesting",
    plantingDate: new Date("2024-02-01"),
    expectedHarvestDate: new Date("2024-11-01"),
    actualHarvestDate: new Date("2024-11-15"),
    numberOfPlants: 400,
    expectedYieldKg: "8000",
    actualYieldKg: "7200",
    notes: "Solo variety, continuous harvest",
    imageUrl: null,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-11-21"),
  },
  {
    id: "demo-crop-6",
    fieldId: "demo-field-1",
    cropType: "avocado",
    variety: "Hass",
    status: "flowering",
    plantingDate: new Date("2021-08-01"),
    expectedHarvestDate: new Date("2025-01-15"),
    actualHarvestDate: null,
    numberOfPlants: 120,
    expectedYieldKg: "3600",
    actualYieldKg: null,
    notes: "Premium Hass for restaurant market",
    imageUrl: null,
    createdAt: new Date("2021-08-01"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-crop-7",
    fieldId: "demo-field-2",
    cropType: "mango",
    variety: "Amelie",
    status: "growing",
    plantingDate: new Date("2024-06-01"),
    expectedHarvestDate: new Date("2026-05-01"),
    actualHarvestDate: null,
    numberOfPlants: 300,
    expectedYieldKg: "15000",
    actualYieldKg: null,
    notes: "New planting, local variety",
    imageUrl: null,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-crop-8",
    fieldId: "demo-field-3",
    cropType: "cashew",
    variety: "Djimba",
    status: "harvested",
    plantingDate: new Date("2020-07-15"),
    expectedHarvestDate: new Date("2024-03-01"),
    actualHarvestDate: new Date("2024-03-15"),
    numberOfPlants: 200,
    expectedYieldKg: "6000",
    actualYieldKg: "5800",
    notes: "Successful harvest, sold to export cooperative",
    imageUrl: null,
    createdAt: new Date("2020-07-15"),
    updatedAt: new Date("2024-03-20"),
  },
];

export const demoTasks: Task[] = [
  {
    id: "demo-task-1",
    title: "Irrigate mango field B2",
    description: "Complete irrigation cycle for the main mango section",
    farmId: "demo-farm-1",
    cropId: null,
    assignedTo: "demo-user-3",
    createdBy: "demo-user-1",
    status: "pending",
    priority: "high",
    dueDate: new Date(),
    completedAt: null,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-task-2",
    title: "Apply fertilizer to cashew plot",
    description: "NPK 15-15-15 application on all cashew trees",
    farmId: "demo-farm-3",
    cropId: null,
    assignedTo: "demo-user-4",
    createdBy: "demo-user-1",
    status: "in_progress",
    priority: "medium",
    dueDate: new Date(Date.now() + 86400000),
    completedAt: null,
    createdAt: new Date("2024-11-19"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-task-3",
    title: "Harvest ripe papayas",
    description: "Collect mature papayas from rows 1-5",
    farmId: "demo-farm-5",
    cropId: null,
    assignedTo: "demo-user-5",
    createdBy: "demo-user-2",
    status: "pending",
    priority: "urgent",
    dueDate: new Date(),
    completedAt: null,
    createdAt: new Date("2024-11-21"),
    updatedAt: new Date("2024-11-21"),
  },
  {
    id: "demo-task-4",
    title: "Pest inspection - pineapple field",
    description: "Weekly pest and disease inspection",
    farmId: "demo-farm-2",
    cropId: null,
    assignedTo: "demo-user-4",
    createdBy: "demo-user-2",
    status: "completed",
    priority: "medium",
    dueDate: new Date(Date.now() - 86400000),
    completedAt: new Date(),
    createdAt: new Date("2024-11-18"),
    updatedAt: new Date("2024-11-21"),
  },
  {
    id: "demo-task-5",
    title: "Prepare new banana planting area",
    description: "Clear and prepare 2 hectares for banana cultivation",
    farmId: "demo-farm-4",
    cropId: null,
    assignedTo: "demo-user-3",
    createdBy: "demo-user-1",
    status: "pending",
    priority: "low",
    dueDate: new Date(Date.now() + 604800000),
    completedAt: null,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-task-6",
    title: "Install drip irrigation system",
    description: "Install new drip irrigation on mango section C",
    farmId: "demo-farm-1",
    cropId: null,
    assignedTo: "demo-user-5",
    createdBy: "demo-user-1",
    status: "in_progress",
    priority: "high",
    dueDate: new Date(Date.now() + 172800000),
    completedAt: null,
    createdAt: new Date("2024-11-17"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-task-7",
    title: "Prune avocado trees",
    description: "Annual pruning for shape and productivity",
    farmId: "demo-farm-4",
    cropId: null,
    assignedTo: "demo-user-4",
    createdBy: "demo-user-1",
    status: "pending",
    priority: "medium",
    dueDate: new Date(Date.now() + 259200000),
    completedAt: null,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-task-8",
    title: "Order seedlings for next season",
    description: "Contact nursery for mango and cashew seedlings",
    farmId: "demo-farm-1",
    cropId: null,
    assignedTo: "demo-user-1",
    createdBy: "demo-user-1",
    status: "completed",
    priority: "medium",
    dueDate: new Date(Date.now() - 172800000),
    completedAt: new Date(Date.now() - 86400000),
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-11-20"),
  },
];

export const demoUsers: User[] = [
  {
    id: "demo-user-1",
    name: "Amadou Diallo",
    email: "amadou.diallo@fructosahel.com",
    phone: "+226 70 12 34 56",
    role: "admin",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-user-2",
    name: "Fatima Traore",
    email: "fatima.traore@fructosahel.com",
    phone: "+223 76 54 32 10",
    role: "manager",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "demo-user-3",
    name: "Ibrahim Ouedraogo",
    email: "ibrahim.o@fructosahel.com",
    phone: "+226 71 23 45 67",
    role: "worker",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-user-4",
    name: "Mariam Keita",
    email: "mariam.keita@fructosahel.com",
    phone: "+227 90 11 22 33",
    role: "worker",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "demo-user-5",
    name: "Jean-Pierre Kabore",
    email: "jp.kabore@fructosahel.com",
    phone: "+226 72 34 56 78",
    role: "worker",
    language: "en",
    avatarUrl: null,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-user-6",
    name: "Aisha Coulibaly",
    email: "aisha.c@fructosahel.com",
    phone: "+223 77 88 99 00",
    role: "viewer",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-11-05"),
  },
];

export const demoTransactions: Transaction[] = [
  {
    id: "demo-tx-1",
    farmId: "demo-farm-1",
    type: "income",
    category: "sales",
    amount: "2500000",
    currency: "XOF",
    description: "Mango export sale to Abidjan buyer",
    transactionDate: new Date("2024-11-20"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-tx-2",
    farmId: "demo-farm-1",
    type: "expense",
    category: "labor",
    amount: "450000",
    currency: "XOF",
    description: "Monthly worker salaries - November",
    transactionDate: new Date("2024-11-15"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-tx-3",
    farmId: "demo-farm-2",
    type: "expense",
    category: "fertilizer",
    amount: "180000",
    currency: "XOF",
    description: "NPK fertilizer purchase",
    transactionDate: new Date("2024-11-10"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "demo-tx-4",
    farmId: "demo-farm-3",
    type: "income",
    category: "sales",
    amount: "1800000",
    currency: "XOF",
    description: "Cashew local market sale",
    transactionDate: new Date("2024-11-18"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-18"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "demo-tx-5",
    farmId: "demo-farm-2",
    type: "income",
    category: "sales",
    amount: "1200000",
    currency: "XOF",
    description: "Pineapple wholesale to supermarket",
    transactionDate: new Date("2024-11-22"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-22"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-tx-6",
    farmId: "demo-farm-4",
    type: "expense",
    category: "equipment",
    amount: "350000",
    currency: "XOF",
    description: "Irrigation pump maintenance",
    transactionDate: new Date("2024-11-12"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-12"),
    updatedAt: new Date("2024-11-12"),
  },
  {
    id: "demo-tx-7",
    farmId: "demo-farm-5",
    type: "expense",
    category: "transport",
    amount: "120000",
    currency: "XOF",
    description: "Truck rental for harvest transport",
    transactionDate: new Date("2024-11-19"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-19"),
    updatedAt: new Date("2024-11-19"),
  },
  {
    id: "demo-tx-8",
    farmId: "demo-farm-1",
    type: "income",
    category: "sales",
    amount: "980000",
    currency: "XOF",
    description: "Avocado local restaurant orders",
    transactionDate: new Date("2024-11-21"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-21"),
    updatedAt: new Date("2024-11-21"),
  },
];

export const demoSales: Sale[] = [
  {
    id: "demo-sale-1",
    farmId: "demo-farm-1",
    cropType: "mango",
    quantityKg: "2500",
    pricePerKg: "1000",
    totalAmount: "2500000",
    currency: "XOF",
    buyerName: "Export Afrique SARL",
    buyerContact: "+225 07 12 34 56",
    saleDate: new Date("2024-11-20"),
    notes: "Premium Kent variety for export",
    createdBy: null,
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "demo-sale-2",
    farmId: "demo-farm-3",
    cropType: "cashew",
    quantityKg: "1200",
    pricePerKg: "1500",
    totalAmount: "1800000",
    currency: "XOF",
    buyerName: "Marche Central Niamey",
    buyerContact: "+227 90 45 67 89",
    saleDate: new Date("2024-11-18"),
    notes: "Raw cashews, grade A",
    createdBy: null,
    createdAt: new Date("2024-11-18"),
  },
  {
    id: "demo-sale-3",
    farmId: "demo-farm-2",
    cropType: "pineapple",
    quantityKg: "800",
    pricePerKg: "1500",
    totalAmount: "1200000",
    currency: "XOF",
    buyerName: "Super Marche Sikasso",
    buyerContact: "+223 78 90 12 34",
    saleDate: new Date("2024-11-22"),
    notes: "Sweet Cayenne variety",
    createdBy: null,
    createdAt: new Date("2024-11-22"),
  },
  {
    id: "demo-sale-4",
    farmId: "demo-farm-4",
    cropType: "banana",
    quantityKg: "600",
    pricePerKg: "500",
    totalAmount: "300000",
    currency: "XOF",
    buyerName: "Hotel Palm Beach",
    buyerContact: "+226 25 30 40 50",
    saleDate: new Date("2024-11-19"),
    notes: "Weekly order for hotel restaurant",
    createdBy: null,
    createdAt: new Date("2024-11-19"),
  },
  {
    id: "demo-sale-5",
    farmId: "demo-farm-5",
    cropType: "papaya",
    quantityKg: "450",
    pricePerKg: "800",
    totalAmount: "360000",
    currency: "XOF",
    buyerName: "Fruits Express Bamako",
    buyerContact: "+223 66 77 88 99",
    saleDate: new Date("2024-11-21"),
    notes: "Solo variety, fully ripe",
    createdBy: null,
    createdAt: new Date("2024-11-21"),
  },
  {
    id: "demo-sale-6",
    farmId: "demo-farm-1",
    cropType: "avocado",
    quantityKg: "350",
    pricePerKg: "2800",
    totalAmount: "980000",
    currency: "XOF",
    buyerName: "Restaurant Le Gourmet",
    buyerContact: "+226 70 11 22 33",
    saleDate: new Date("2024-11-21"),
    notes: "Hass variety for restaurant chain",
    createdBy: null,
    createdAt: new Date("2024-11-21"),
  },
];

// Helper to calculate transaction totals
export function calculateTransactionTotals(transactions: Transaction[]) {
  const income = transactions
    .filter((t) => t.type === "income")
    .reduce((sum, t) => sum + parseFloat(t.amount), 0);

  const expense = transactions
    .filter((t) => t.type === "expense")
    .reduce((sum, t) => sum + parseFloat(t.amount), 0);

  return {
    income,
    expense,
    balance: income - expense,
  };
}

// Roadmap phases modeled on the 7-year Sahel farm plan
export const demoRoadmapPhases: RoadmapPhase[] = [
  {
    id: "demo-phase-1",
    farmId: "demo-farm-1",
    name: "Foundation & Infrastructure",
    description:
      "Establish the 1 ha core site with fencing, water infrastructure, composting system, and first moringa + cowpea plantings. Build the chicken coop and introduce first poultry flock.",
    phaseNumber: 1,
    status: "completed",
    targetStartDate: new Date("2025-01-01"),
    targetEndDate: new Date("2025-12-31"),
    actualStartDate: new Date("2025-01-15"),
    actualEndDate: new Date("2025-11-30"),
    targetHectares: "1",
    targetRevenueUsd: "44000",
    notes: "Year 1 complete. Exceeded revenue target by 8%.",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-12-01"),
  },
  {
    id: "demo-phase-2",
    farmId: "demo-farm-1",
    name: "Expansion to 5 ha",
    description:
      "Scale to 5 ha with drip irrigation. Add mango orchard, sorghum, and pearl millet rotation. Introduce guinea fowl and expand chicken operation. First cash crop sales to local markets.",
    phaseNumber: 2,
    status: "in_progress",
    targetStartDate: new Date("2026-01-01"),
    targetEndDate: new Date("2026-12-31"),
    actualStartDate: new Date("2026-01-10"),
    actualEndDate: null,
    targetHectares: "5",
    targetRevenueUsd: "120000",
    notes: "On track for mid-year mango planting.",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    id: "demo-phase-3",
    farmId: "demo-farm-1",
    name: "Full Crop Rotation (10 ha)",
    description:
      "Reach 10 ha under cultivation. Implement full crop rotation with cowpea, bambara groundnut, peanut, and pigeon pea as nitrogen fixers between fruit tree rows. Begin processing dried moringa leaf for export.",
    phaseNumber: 3,
    status: "not_started",
    targetStartDate: new Date("2027-01-01"),
    targetEndDate: new Date("2027-12-31"),
    actualStartDate: null,
    actualEndDate: null,
    targetHectares: "10",
    targetRevenueUsd: "280000",
    notes: null,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "demo-phase-4",
    farmId: "demo-farm-1",
    name: "Maturation & Market Access (25 ha)",
    description:
      "Scale to 25 ha. Mango and cashew orchards reach full production. Add citrus and guava. Establish cooperative buying agreements and cold chain logistics for export.",
    phaseNumber: 4,
    status: "not_started",
    targetStartDate: new Date("2028-01-01"),
    targetEndDate: new Date("2029-12-31"),
    actualStartDate: null,
    actualEndDate: null,
    targetHectares: "25",
    targetRevenueUsd: "680000",
    notes: null,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "demo-phase-5",
    farmId: "demo-farm-1",
    name: "Regional Hub (175 ha vision)",
    description:
      "Long-term vision to become a regional agricultural hub. Integrate satellite farms under cooperative model, processing facility for dried fruit and moringa powder, and training center for neighboring farmers.",
    phaseNumber: 5,
    status: "not_started",
    targetStartDate: new Date("2030-01-01"),
    targetEndDate: new Date("2031-12-31"),
    actualStartDate: null,
    actualEndDate: null,
    targetHectares: "175",
    targetRevenueUsd: "1460000",
    notes: null,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
];

export const demoMilestones: Milestone[] = [
  // Phase 1 milestones
  {
    id: "demo-ms-1",
    phaseId: "demo-phase-1",
    title: "Fence and secure 1 ha core site",
    description: "Install perimeter fencing with thorny hedge (Ziziphus) as living fence backup.",
    category: "infrastructure",
    status: "completed",
    targetDate: new Date("2025-03-01"),
    completedDate: new Date("2025-02-20"),
    sortOrder: 1,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-02-20"),
  },
  {
    id: "demo-ms-2",
    phaseId: "demo-phase-1",
    title: "Install borehole and water tank",
    description: "Drill borehole to 60m, install solar pump and 5000L elevated tank for gravity-fed irrigation.",
    category: "infrastructure",
    status: "completed",
    targetDate: new Date("2025-04-01"),
    completedDate: new Date("2025-04-15"),
    sortOrder: 2,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-04-15"),
  },
  {
    id: "demo-ms-3",
    phaseId: "demo-phase-1",
    title: "Plant first moringa grove (0.25 ha)",
    description: "Establish moringa oleifera nursery and transplant to permanent site. First leaf harvest at 3 months.",
    category: "crops",
    status: "completed",
    targetDate: new Date("2025-05-01"),
    completedDate: new Date("2025-05-10"),
    sortOrder: 3,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-05-10"),
  },
  {
    id: "demo-ms-4",
    phaseId: "demo-phase-1",
    title: "Build chicken coop for 50 birds",
    description: "Construct ventilated coop with local materials. Start with 50 dual-purpose hens for eggs and meat.",
    category: "livestock",
    status: "completed",
    targetDate: new Date("2025-06-01"),
    completedDate: new Date("2025-06-05"),
    sortOrder: 4,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-06-05"),
  },
  {
    id: "demo-ms-5",
    phaseId: "demo-phase-1",
    title: "First cowpea harvest and sale",
    description: "Harvest cowpea intercrop from moringa rows. Target 200 kg for local market.",
    category: "financial",
    status: "completed",
    targetDate: new Date("2025-09-01"),
    completedDate: new Date("2025-09-12"),
    sortOrder: 5,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-09-12"),
  },
  // Phase 2 milestones
  {
    id: "demo-ms-6",
    phaseId: "demo-phase-2",
    title: "Install drip irrigation on 5 ha",
    description: "Extend solar-powered drip system from borehole to cover expanded growing area.",
    category: "infrastructure",
    status: "in_progress",
    targetDate: new Date("2026-03-01"),
    completedDate: null,
    sortOrder: 1,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-02-15"),
  },
  {
    id: "demo-ms-7",
    phaseId: "demo-phase-2",
    title: "Plant 200 mango saplings (Kent + Amelie)",
    description: "Establish mango orchard with mixed export (Kent) and local (Amelie) varieties at 10m spacing.",
    category: "crops",
    status: "not_started",
    targetDate: new Date("2026-06-15"),
    completedDate: null,
    sortOrder: 2,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "demo-ms-8",
    phaseId: "demo-phase-2",
    title: "Introduce guinea fowl flock (100 birds)",
    description: "Guinea fowl for pest control in orchards and income from meat/eggs.",
    category: "livestock",
    status: "not_started",
    targetDate: new Date("2026-04-01"),
    completedDate: null,
    sortOrder: 3,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "demo-ms-9",
    phaseId: "demo-phase-2",
    title: "Achieve $10K monthly revenue",
    description: "Consistent monthly revenue from moringa powder, cowpea, eggs, and early fruit sales.",
    category: "financial",
    status: "not_started",
    targetDate: new Date("2026-10-01"),
    completedDate: null,
    sortOrder: 4,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  // Phase 3 milestones
  {
    id: "demo-ms-10",
    phaseId: "demo-phase-3",
    title: "Implement full crop rotation system",
    description: "Rotate legumes (cowpea, bambara, peanut, pigeon pea) as intercrops between fruit tree rows on 10 ha.",
    category: "crops",
    status: "not_started",
    targetDate: new Date("2027-05-01"),
    completedDate: null,
    sortOrder: 1,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "demo-ms-11",
    phaseId: "demo-phase-3",
    title: "Launch moringa powder processing",
    description: "Set up solar dryer and small grinding mill. Package moringa leaf powder for export.",
    category: "processing",
    status: "not_started",
    targetDate: new Date("2027-06-01"),
    completedDate: null,
    sortOrder: 2,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "demo-ms-12",
    phaseId: "demo-phase-3",
    title: "Purchase tractor and implements",
    description: "Acquire compact tractor with plow, disc harrow, and trailer for 10+ ha operations.",
    category: "equipment",
    status: "not_started",
    targetDate: new Date("2027-02-01"),
    completedDate: null,
    sortOrder: 3,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  // Phase 4 milestones
  {
    id: "demo-ms-13",
    phaseId: "demo-phase-4",
    title: "First mango export shipment",
    description: "Kent mango trees reach production maturity. First export to EU market via cooperative.",
    category: "financial",
    status: "not_started",
    targetDate: new Date("2028-05-01"),
    completedDate: null,
    sortOrder: 1,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "demo-ms-14",
    phaseId: "demo-phase-4",
    title: "Establish cold chain storage",
    description: "Build solar-powered cold room for post-harvest storage of mangoes, citrus, and vegetables.",
    category: "infrastructure",
    status: "not_started",
    targetDate: new Date("2028-03-01"),
    completedDate: null,
    sortOrder: 2,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  // Phase 5 milestone
  {
    id: "demo-ms-15",
    phaseId: "demo-phase-5",
    title: "Open farmer training center",
    description: "Establish training facility to share integrated farming techniques with 500+ neighboring farmers annually.",
    category: "other",
    status: "not_started",
    targetDate: new Date("2030-06-01"),
    completedDate: null,
    sortOrder: 1,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
];

export const demoLivestock: Livestock[] = [
  {
    id: "demo-livestock-1",
    farmId: "demo-farm-1",
    livestockType: "chickens",
    breed: "Local dual-purpose",
    quantity: 120,
    notes: "Free-range layers producing ~80 eggs/day. Supplemented with farm grain.",
    createdAt: new Date("2025-06-05"),
    updatedAt: new Date("2026-01-15"),
  },
  {
    id: "demo-livestock-2",
    farmId: "demo-farm-1",
    livestockType: "guinea_fowl",
    breed: "Helmeted guinea fowl",
    quantity: 45,
    notes: "Pest control in orchard rows. Excellent tick and termite reduction.",
    createdAt: new Date("2025-09-01"),
    updatedAt: new Date("2026-01-10"),
  },
  {
    id: "demo-livestock-3",
    farmId: "demo-farm-1",
    livestockType: "sheep",
    breed: "Djallonke",
    quantity: 15,
    notes: "Browse management between tree rows. Sold for Tabaski season.",
    createdAt: new Date("2025-08-01"),
    updatedAt: new Date("2026-01-05"),
  },
  {
    id: "demo-livestock-4",
    farmId: "demo-farm-2",
    livestockType: "ducks",
    breed: "Muscovy",
    quantity: 30,
    notes: "Slug and snail control in pineapple fields. Dual income from eggs and meat.",
    createdAt: new Date("2025-07-15"),
    updatedAt: new Date("2025-12-20"),
  },
  {
    id: "demo-livestock-5",
    farmId: "demo-farm-3",
    livestockType: "chickens",
    breed: "ISA Brown",
    quantity: 200,
    notes: "Commercial layer operation supplying eggs to Maradi market.",
    createdAt: new Date("2025-03-01"),
    updatedAt: new Date("2026-02-01"),
  },
];

// Helper to calculate sales totals
export function calculateSalesTotals(sales: Sale[]) {
  const totalRevenue = sales.reduce(
    (sum, s) => sum + parseFloat(s.totalAmount),
    0,
  );
  const totalQuantity = sales.reduce(
    (sum, s) => sum + parseFloat(s.quantityKg),
    0,
  );

  return {
    totalRevenue,
    totalQuantity,
    salesCount: sales.length,
  };
}
