// Demo data for dashboard pages when database is empty

import type { Farm, Task, User, Transaction, Sale, Crop } from "@/types";

export const demoFarms: Farm[] = [
  {
    id: "demo-farm-1",
    name: "Ferme Manguier Bobo",
    location: "Bobo-Dioulasso",
    country: "burkina_faso",
    sizeHectares: "45.5",
    latitude: "11.1771",
    longitude: "-4.2979",
    description: "Main mango and cashew production farm with irrigation system",
    managerId: "demo-user-1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-farm-2",
    name: "Ferme Ananas Sikasso",
    location: "Sikasso",
    country: "mali",
    sizeHectares: "32.0",
    latitude: "11.3167",
    longitude: "-5.6667",
    description: "Pineapple and banana plantation near the river",
    managerId: "demo-user-2",
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "demo-farm-3",
    name: "Ferme Cashew Maradi",
    location: "Maradi",
    country: "niger",
    sizeHectares: "28.5",
    latitude: "13.5000",
    longitude: "7.1000",
    description: "Cashew and papaya farm with drip irrigation",
    managerId: "demo-user-3",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-farm-4",
    name: "Ferme Banane Ouaga",
    location: "Ouagadougou",
    country: "burkina_faso",
    sizeHectares: "18.0",
    latitude: "12.3714",
    longitude: "-1.5197",
    description: "Urban banana and avocado farm",
    managerId: "demo-user-1",
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-farm-5",
    name: "Ferme Papaye Bamako",
    location: "Bamako",
    country: "mali",
    sizeHectares: "22.0",
    latitude: "12.6392",
    longitude: "-8.0029",
    description: "Papaya and mango cooperative farm",
    managerId: "demo-user-2",
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-11-10"),
  },
];

export const demoCrops: Crop[] = [
  {
    id: "demo-crop-1",
    fieldId: "demo-field-1",
    cropType: "mango",
    variety: "Kent",
    status: "fruiting",
    plantingDate: new Date("2022-06-15"),
    expectedHarvestDate: new Date("2024-12-01"),
    actualHarvestDate: null,
    numberOfPlants: 250,
    expectedYieldKg: "12500",
    actualYieldKg: null,
    notes: "Premium export variety, third season",
    createdAt: new Date("2022-06-15"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-crop-2",
    fieldId: "demo-field-2",
    cropType: "cashew",
    variety: "Local improved",
    status: "growing",
    plantingDate: new Date("2023-07-01"),
    expectedHarvestDate: new Date("2025-02-15"),
    actualHarvestDate: null,
    numberOfPlants: 180,
    expectedYieldKg: "5400",
    actualYieldKg: null,
    notes: "First harvest expected next year",
    createdAt: new Date("2023-07-01"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "demo-crop-3",
    fieldId: "demo-field-3",
    cropType: "pineapple",
    variety: "Cayenne",
    status: "harvesting",
    plantingDate: new Date("2024-01-15"),
    expectedHarvestDate: new Date("2024-11-30"),
    actualHarvestDate: null,
    numberOfPlants: 5000,
    expectedYieldKg: "7500",
    actualYieldKg: "6800",
    notes: "Sweet Cayenne for local market",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-crop-4",
    fieldId: "demo-field-4",
    cropType: "banana",
    variety: "Plantain",
    status: "fruiting",
    plantingDate: new Date("2024-03-01"),
    expectedHarvestDate: new Date("2024-12-15"),
    actualHarvestDate: null,
    numberOfPlants: 800,
    expectedYieldKg: "16000",
    actualYieldKg: null,
    notes: "Organic plantain for hotels",
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-11-19"),
  },
  {
    id: "demo-crop-5",
    fieldId: "demo-field-5",
    cropType: "papaya",
    variety: "Solo",
    status: "harvesting",
    plantingDate: new Date("2024-02-01"),
    expectedHarvestDate: new Date("2024-11-01"),
    actualHarvestDate: new Date("2024-11-15"),
    numberOfPlants: 400,
    expectedYieldKg: "8000",
    actualYieldKg: "7200",
    notes: "Solo variety, continuous harvest",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-11-21"),
  },
  {
    id: "demo-crop-6",
    fieldId: "demo-field-1",
    cropType: "avocado",
    variety: "Hass",
    status: "flowering",
    plantingDate: new Date("2021-08-01"),
    expectedHarvestDate: new Date("2025-01-15"),
    actualHarvestDate: null,
    numberOfPlants: 120,
    expectedYieldKg: "3600",
    actualYieldKg: null,
    notes: "Premium Hass for restaurant market",
    createdAt: new Date("2021-08-01"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-crop-7",
    fieldId: "demo-field-2",
    cropType: "mango",
    variety: "Amelie",
    status: "growing",
    plantingDate: new Date("2024-06-01"),
    expectedHarvestDate: new Date("2026-05-01"),
    actualHarvestDate: null,
    numberOfPlants: 300,
    expectedYieldKg: "15000",
    actualYieldKg: null,
    notes: "New planting, local variety",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-crop-8",
    fieldId: "demo-field-3",
    cropType: "cashew",
    variety: "Djimba",
    status: "harvested",
    plantingDate: new Date("2020-07-15"),
    expectedHarvestDate: new Date("2024-03-01"),
    actualHarvestDate: new Date("2024-03-15"),
    numberOfPlants: 200,
    expectedYieldKg: "6000",
    actualYieldKg: "5800",
    notes: "Successful harvest, sold to export cooperative",
    createdAt: new Date("2020-07-15"),
    updatedAt: new Date("2024-03-20"),
  },
];

export const demoTasks: Task[] = [
  {
    id: "demo-task-1",
    title: "Irrigate mango field B2",
    description: "Complete irrigation cycle for the main mango section",
    farmId: "demo-farm-1",
    cropId: null,
    assignedTo: "demo-user-3",
    createdBy: "demo-user-1",
    status: "pending",
    priority: "high",
    dueDate: new Date(),
    completedAt: null,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-task-2",
    title: "Apply fertilizer to cashew plot",
    description: "NPK 15-15-15 application on all cashew trees",
    farmId: "demo-farm-3",
    cropId: null,
    assignedTo: "demo-user-4",
    createdBy: "demo-user-1",
    status: "in_progress",
    priority: "medium",
    dueDate: new Date(Date.now() + 86400000),
    completedAt: null,
    createdAt: new Date("2024-11-19"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-task-3",
    title: "Harvest ripe papayas",
    description: "Collect mature papayas from rows 1-5",
    farmId: "demo-farm-5",
    cropId: null,
    assignedTo: "demo-user-5",
    createdBy: "demo-user-2",
    status: "pending",
    priority: "urgent",
    dueDate: new Date(),
    completedAt: null,
    createdAt: new Date("2024-11-21"),
    updatedAt: new Date("2024-11-21"),
  },
  {
    id: "demo-task-4",
    title: "Pest inspection - pineapple field",
    description: "Weekly pest and disease inspection",
    farmId: "demo-farm-2",
    cropId: null,
    assignedTo: "demo-user-4",
    createdBy: "demo-user-2",
    status: "completed",
    priority: "medium",
    dueDate: new Date(Date.now() - 86400000),
    completedAt: new Date(),
    createdAt: new Date("2024-11-18"),
    updatedAt: new Date("2024-11-21"),
  },
  {
    id: "demo-task-5",
    title: "Prepare new banana planting area",
    description: "Clear and prepare 2 hectares for banana cultivation",
    farmId: "demo-farm-4",
    cropId: null,
    assignedTo: "demo-user-3",
    createdBy: "demo-user-1",
    status: "pending",
    priority: "low",
    dueDate: new Date(Date.now() + 604800000),
    completedAt: null,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-task-6",
    title: "Install drip irrigation system",
    description: "Install new drip irrigation on mango section C",
    farmId: "demo-farm-1",
    cropId: null,
    assignedTo: "demo-user-5",
    createdBy: "demo-user-1",
    status: "in_progress",
    priority: "high",
    dueDate: new Date(Date.now() + 172800000),
    completedAt: null,
    createdAt: new Date("2024-11-17"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-task-7",
    title: "Prune avocado trees",
    description: "Annual pruning for shape and productivity",
    farmId: "demo-farm-4",
    cropId: null,
    assignedTo: "demo-user-4",
    createdBy: "demo-user-1",
    status: "pending",
    priority: "medium",
    dueDate: new Date(Date.now() + 259200000),
    completedAt: null,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-task-8",
    title: "Order seedlings for next season",
    description: "Contact nursery for mango and cashew seedlings",
    farmId: "demo-farm-1",
    cropId: null,
    assignedTo: "demo-user-1",
    createdBy: "demo-user-1",
    status: "completed",
    priority: "medium",
    dueDate: new Date(Date.now() - 172800000),
    completedAt: new Date(Date.now() - 86400000),
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-11-20"),
  },
];

export const demoUsers: User[] = [
  {
    id: "demo-user-1",
    name: "Amadou Diallo",
    email: "amadou.diallo@fructosahel.com",
    phone: "+226 70 12 34 56",
    role: "admin",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-user-2",
    name: "Fatima Traore",
    email: "fatima.traore@fructosahel.com",
    phone: "+223 76 54 32 10",
    role: "manager",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "demo-user-3",
    name: "Ibrahim Ouedraogo",
    email: "ibrahim.o@fructosahel.com",
    phone: "+226 71 23 45 67",
    role: "worker",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-user-4",
    name: "Mariam Keita",
    email: "mariam.keita@fructosahel.com",
    phone: "+227 90 11 22 33",
    role: "worker",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "demo-user-5",
    name: "Jean-Pierre Kabore",
    email: "jp.kabore@fructosahel.com",
    phone: "+226 72 34 56 78",
    role: "worker",
    language: "en",
    avatarUrl: null,
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-user-6",
    name: "Aisha Coulibaly",
    email: "aisha.c@fructosahel.com",
    phone: "+223 77 88 99 00",
    role: "viewer",
    language: "fr",
    avatarUrl: null,
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-11-05"),
  },
];

export const demoTransactions: Transaction[] = [
  {
    id: "demo-tx-1",
    farmId: "demo-farm-1",
    type: "income",
    category: "sales",
    amount: "2500000",
    currency: "XOF",
    description: "Mango export sale to Abidjan buyer",
    transactionDate: new Date("2024-11-20"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "demo-tx-2",
    farmId: "demo-farm-1",
    type: "expense",
    category: "labor",
    amount: "450000",
    currency: "XOF",
    description: "Monthly worker salaries - November",
    transactionDate: new Date("2024-11-15"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "demo-tx-3",
    farmId: "demo-farm-2",
    type: "expense",
    category: "fertilizer",
    amount: "180000",
    currency: "XOF",
    description: "NPK fertilizer purchase",
    transactionDate: new Date("2024-11-10"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "demo-tx-4",
    farmId: "demo-farm-3",
    type: "income",
    category: "sales",
    amount: "1800000",
    currency: "XOF",
    description: "Cashew local market sale",
    transactionDate: new Date("2024-11-18"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-18"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "demo-tx-5",
    farmId: "demo-farm-2",
    type: "income",
    category: "sales",
    amount: "1200000",
    currency: "XOF",
    description: "Pineapple wholesale to supermarket",
    transactionDate: new Date("2024-11-22"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-22"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "demo-tx-6",
    farmId: "demo-farm-4",
    type: "expense",
    category: "equipment",
    amount: "350000",
    currency: "XOF",
    description: "Irrigation pump maintenance",
    transactionDate: new Date("2024-11-12"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-12"),
    updatedAt: new Date("2024-11-12"),
  },
  {
    id: "demo-tx-7",
    farmId: "demo-farm-5",
    type: "expense",
    category: "transport",
    amount: "120000",
    currency: "XOF",
    description: "Truck rental for harvest transport",
    transactionDate: new Date("2024-11-19"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-19"),
    updatedAt: new Date("2024-11-19"),
  },
  {
    id: "demo-tx-8",
    farmId: "demo-farm-1",
    type: "income",
    category: "sales",
    amount: "980000",
    currency: "XOF",
    description: "Avocado local restaurant orders",
    transactionDate: new Date("2024-11-21"),
    createdBy: null,
    attachmentUrl: null,
    createdAt: new Date("2024-11-21"),
    updatedAt: new Date("2024-11-21"),
  },
];

export const demoSales: Sale[] = [
  {
    id: "demo-sale-1",
    farmId: "demo-farm-1",
    cropType: "mango",
    quantityKg: "2500",
    pricePerKg: "1000",
    totalAmount: "2500000",
    currency: "XOF",
    buyerName: "Export Afrique SARL",
    buyerContact: "+225 07 12 34 56",
    saleDate: new Date("2024-11-20"),
    notes: "Premium Kent variety for export",
    createdBy: null,
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "demo-sale-2",
    farmId: "demo-farm-3",
    cropType: "cashew",
    quantityKg: "1200",
    pricePerKg: "1500",
    totalAmount: "1800000",
    currency: "XOF",
    buyerName: "Marche Central Niamey",
    buyerContact: "+227 90 45 67 89",
    saleDate: new Date("2024-11-18"),
    notes: "Raw cashews, grade A",
    createdBy: null,
    createdAt: new Date("2024-11-18"),
  },
  {
    id: "demo-sale-3",
    farmId: "demo-farm-2",
    cropType: "pineapple",
    quantityKg: "800",
    pricePerKg: "1500",
    totalAmount: "1200000",
    currency: "XOF",
    buyerName: "Super Marche Sikasso",
    buyerContact: "+223 78 90 12 34",
    saleDate: new Date("2024-11-22"),
    notes: "Sweet Cayenne variety",
    createdBy: null,
    createdAt: new Date("2024-11-22"),
  },
  {
    id: "demo-sale-4",
    farmId: "demo-farm-4",
    cropType: "banana",
    quantityKg: "600",
    pricePerKg: "500",
    totalAmount: "300000",
    currency: "XOF",
    buyerName: "Hotel Palm Beach",
    buyerContact: "+226 25 30 40 50",
    saleDate: new Date("2024-11-19"),
    notes: "Weekly order for hotel restaurant",
    createdBy: null,
    createdAt: new Date("2024-11-19"),
  },
  {
    id: "demo-sale-5",
    farmId: "demo-farm-5",
    cropType: "papaya",
    quantityKg: "450",
    pricePerKg: "800",
    totalAmount: "360000",
    currency: "XOF",
    buyerName: "Fruits Express Bamako",
    buyerContact: "+223 66 77 88 99",
    saleDate: new Date("2024-11-21"),
    notes: "Solo variety, fully ripe",
    createdBy: null,
    createdAt: new Date("2024-11-21"),
  },
  {
    id: "demo-sale-6",
    farmId: "demo-farm-1",
    cropType: "avocado",
    quantityKg: "350",
    pricePerKg: "2800",
    totalAmount: "980000",
    currency: "XOF",
    buyerName: "Restaurant Le Gourmet",
    buyerContact: "+226 70 11 22 33",
    saleDate: new Date("2024-11-21"),
    notes: "Hass variety for restaurant chain",
    createdBy: null,
    createdAt: new Date("2024-11-21"),
  },
];

// Helper to calculate transaction totals
export function calculateTransactionTotals(transactions: Transaction[]) {
  const income = transactions
    .filter(t => t.type === "income")
    .reduce((sum, t) => sum + parseFloat(t.amount), 0);

  const expense = transactions
    .filter(t => t.type === "expense")
    .reduce((sum, t) => sum + parseFloat(t.amount), 0);

  return {
    income,
    expense,
    balance: income - expense,
  };
}

// Helper to calculate sales totals
export function calculateSalesTotals(sales: Sale[]) {
  const totalRevenue = sales.reduce((sum, s) => sum + parseFloat(s.totalAmount), 0);
  const totalQuantity = sales.reduce((sum, s) => sum + parseFloat(s.quantityKg), 0);

  return {
    totalRevenue,
    totalQuantity,
    salesCount: sales.length,
  };
}
